spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/smartacademy
    username: postgres
    password: root123
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
